// <auto-generated />
using System;
using InteractivePresentation.Domain.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("InteractivePresentation.Domain.Entity.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PollId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("InteractivePresentation.Domain.Entity.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PollId")
                        .HasAnnotation("Relational:JsonPropertyName", "poll_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "presentation_id");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("InteractivePresentation.Domain.Entity.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("VoteId")
                        .HasAnnotation("Relational:JsonPropertyName", "vote_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "client_id");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "key");

                    b.Property<Guid>("PollId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "poll_id");

                    b.HasKey("Id");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("InteractivePresentation.Domain.Entity.Option", b =>
                {
                    b.HasOne("InteractivePresentation.Domain.Entity.Poll", null)
                        .WithMany("Options")
                        .HasForeignKey("PollId");
                });

            modelBuilder.Entity("InteractivePresentation.Domain.Entity.Poll", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
